project_id = "njnmspciqlwilrbbrcmc"

[functions.whatsapp-api]
verify_jwt = false

[functions.google-sheets]
verify_jwt = false

[functions.meta-marketing]
verify_jwt = true
[functions.whatsapp-onboard]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-onboard/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-onboard/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-onboard/*.html" ]
